# Generated by Django 4.2.4 on 2023-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="images/")),
                ("email", models.EmailField(max_length=100)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cofee_name", models.CharField(max_length=25)),
                ("big_price", models.PositiveIntegerField(default=0)),
                ("small_price", models.PositiveIntegerField(default=0)),
                ("img", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Sarlavha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cafe_name", models.CharField(max_length=30)),
                ("bio", models.CharField(max_length=15)),
                ("about", models.CharField(max_length=200)),
            ],
        ),
    ]
