# Generated by Django 4.2.4 on 2023-09-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="img",
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(default=0, max_length=22),
            preserve_default=False,
        ),
    ]
